### ISSUE TITLE
Hacer que el flujo redirija al usuario a otros flujos segun las respuestas a ciertas preguntas en la clarificacion

### ISSUE THREAD

**Issue by Jose-Simon-Pepe** [Jose-Simon-Pepe/autorg_from_ddd#11]

**Comment by Jose-Simon-Pepe** [comment]
Podriamos usar el patron strategy para esto, que sea implementado por el servicio flujo para asi mantener una funcionalidad de "flujo" y hacerlo interactivo con el objeto Respuesta @idcmardelplata

**Comment by idcmardelplata** [comment]
Podríamos, pero creo que seria mejor poder entender todo el flujo por completo antes y luego armar un modelo ya que hay varios triggers que suceden en gtd y que podemos pasar por alto si no tenemos una visión un poco mas holistica del sistema.
