### ISSUE TITLE
Spec: Make bdd's specifications for the know behavior in Clarification

### ISSUE THREAD

**Issue by Jose-Simon-Pepe** [Jose-Simon-Pepe/autorg_from_ddd#16]
To define system's behavior according to Clarification process.
If a new model word or concept appears, it must be documented.

**Comment by Jose-Simon-Pepe** [comment]
Behave should be configured to search into docs/features/steps for steps to run, instead to be neccesary for one to go into docs features, moving cwd each time. @Jose-Simon-Pepe

**Comment by idcmardelplata** [comment]
@Jose-Simon-Pepe En realidad lo que deberíamos poner en los ficheros de bdd es el comportamiento esperado. Por ende deberíamos armar escenarios donde podamos simular distintos flujos de ejecución. Recordar que con bdd se prueba el comportamiento mas no el diseño en si.

**Comment by Jose-Simon-Pepe** [comment]
> @Jose-Simon-Pepe En realidad lo que deberíamos poner en los ficheros de bdd es el comportamiento esperado. Por ende deberíamos armar escenarios donde podamos simular distintos flujos de ejecución. Recordar que con bdd se prueba el comportamiento mas no el diseño en si.
Genial. En base a eso trabaje la especificacion de la clarificacion de no accionables(5f16927...907214d), y al terminar de especificar los accionables entonces cerrare el issue.
