### ISSUE TITLE
add metadata to inputs

### ISSUE THREAD

**Issue by idcmardelplata** [Jose-Simon-Pepe/autorg_from_ddd#21]
Dado que los inputs pueden agregarse en cualquier momento,
puede llegar a ser muy util agregar una fecha y hora junto con el contenido del input.
Esto habilitaría que el día de mañana podamos agregar funcionalidad de búsqueda por fecha
y diferentes maneras de poder listar los inputs para ser clarificados.

El issue #9 plantea este mecanismo.

**Comment by Jose-Simon-Pepe** [comment]
De acuerdo. Ademas, dado que en el proceso, en la etapa de ordenar inputs, se requiere eliminar los inputs que el usuario no desea finalmente procesar, entonces nos puede servir como dato de identificacion sobre los inputs.

**Comment by idcmardelplata** [comment]
Los inputs ya tienen metadata (el id y la fecha de creacion son metadatos)
