### ISSUE TITLE
CLI should recieve what kind of repo to be used in App instantiation

### ISSUE THREAD

**Issue by Jose-Simon-Pepe** [Jose-Simon-Pepe/autorg_from_ddd#26]
Hola @idcmardelplata :smiling_face_with_tear: 
Tenemos un problema en las **pruebas de integracion** _en el archivo tests/infrastructure/test_cli_ que imposibilita pruebas de integracion del componente **cli click**. 
El asunto es que es **imposible vaciar el repositorio**, si lo hacemos como llamada desde cli entonces nos acoplamos con la tarea de crear un comando que elimine inputs del inbox, si tratamos de usar un stub entonces no podemos inyectarlo porque es el cli quien instancia el tipo de app con el tipo de repo a usar.
¿Deberiamos hacer que cli reciba de alguna manera esto, o se te ocurre otra forma de encarar la integracion?
Con todo mi respeto, admiracion, y una docena de facturas para usted :heart:

**Comment by idcmardelplata** [comment]
En realidad eso es un tema de configuracion.
Deberiamos tener un modulo de configuracion donde podamos leer desde y hacia donde va a almacenar los inputs,
por ahora lo pusimos directamente en el csv puesto que no tenemos decidida cual va a ser la base de datos que usemos
para esta tarea (ni sus parametros de configuracion) :)

**Comment by idcmardelplata** [comment]
No hay problema con eso porque justamente lo que se esta probando en las pruebas de integración es la "INTEGRACIÓN DE TODOS LOS COMPONENTES JUNTOS", luego debemos crear un comando para listar los inputs y otro para eliminarlos, cuando estén esos comandos podemos re usarlos para las pruebas. Igualmente fíjate que en algunas pruebas simplemente cree un método teardown() que se encargaba de eliminar automáticamente el fichero csv después de cada prueba, podrías usar ese aproach mientras tanto.
