### ISSUE TITLE
me quede sin whatsapp ;(

### ISSUE THREAD

**Issue by idcmardelplata** [Jose-Simon-Pepe/autorg_from_ddd#27]
Hola josu espero que leas este issue.
Mira whatsdesk ya murio en mi compu (se cerro el hdp).
Hoy voy a tratar de comprarme un telefono en personal pero
si no llego a poder hacerlo mañana a la 1 nos conectamos por zoom como siempre.

Por si las moscas te paso mis datos de telegram. 
usuario: @idcmardelplata
telefono: +54 2236687186
id: Martin Cho.

Un abrazo viejo y me encantan los cambios que le estas pegando al proyecto :)

**Comment by Jose-Simon-Pepe** [comment]
Hola Martu. 
No tengo telegram, en el caso de que estés incomunicado mas tiempo que hoy, me la descargo y te hablo x ahi.
Voy a seguir con el proyecto mientras. Un abrazo, joven.

**Comment by idcmardelplata** [comment]
Si podes porfa instalatelo ya que hoy no me pude comprar el teléfono ;(

**Comment by idcmardelplata** [comment]
Che me olvide de decirte, si no queres instalar telegram en el telefono podes
instalar telegram-desktop en linux y listo :)
