### ISSUE TITLE
Is necessary add this repository to github projects

### ISSUE THREAD

**Issue by idcmardelplata** [Jose-Simon-Pepe/autorg_from_ddd#3]
Esto nos permite poder organizar y gestionar las tareas del proyecto en un panel kanban propio. De esta manera podemos ver que tareas tenemos pendiente, en cuales estamos trabajando, cuales son las dependencias y prioridades entre las tareas, asignarles fecha de finalizacion etc.. Todo integrado desde un mismo repositorio.

**Comment by Jose-Simon-Pepe** [comment]
Done

**Comment by idcmardelplata** [comment]
Reabrí el issue porque todavía no esta creado el proyecto. Una vez creado lo cerramos (así es mas fácil trackear las cosas que tenemos pendientes @Jose-Simon-Pepe) :+1:

**Comment by idcmardelplata** [comment]
Done
