### ISSUE TITLE
Refactorizar el codigo prod test actual para evitar dificultad de desarrollo

### ISSUE THREAD

**Issue by Jose-Simon-Pepe** [Jose-Simon-Pepe/autorg_from_ddd#4]
- [ ] tests
    - [x] Todos: Implementar tests classes. Si es necesario usar mark parametrizer para unificar parametros
    - [x] Utilizar dobles de prueba para los componentes externos
    - [x] Flow: Aumentar la legibilidad atomizando los tests: descomponerlos, asegurarme de estar probando unitariamente
    - [x] Todos: Valorar si implementar data factories para reutilizar e integrar test data
- [ ] prod
    - [x] Todos: Para componentes externos utilizar interfaces, nunca importar componentes implementados
    - [ ] TODOS: Add data tipes

**Comment by idcmardelplata** [comment]
Me encanta, estoy totalmente de acuerdo con eso. :100:
